import 'core-js/proposals/reflect-metadata';
import 'zone.js/dist/zone';
import 'chart.js/dist/Chart.js';
import 'hammerjs/hammer.min.js';
import 'jquery/dist/jquery.min.js';
import 'popper.js/dist/umd/popper.min.js';
import 'bootstrap/dist/js/bootstrap.min.js';
import 'owl.carousel/dist/owl.carousel.js';
import 'quill/dist/quill.js';
require('../manifest.webapp');
