# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.realestatebrokerage: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/realestatebrokerage?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: UTC
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.search:
        lucene_version: LATEST
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: smtp.gmail.com
    port: 587
    username: bdscompanyvietnam@gmail.com
    password: ngovandon
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8080

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
  cache: # Cache configuration
    ehcache: # Ehcache configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
      max-entries: 100 # Number of objects in each cache entry
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: ZTViYzljN2IxMTZlNjc3YmE3MjY3ODA4MGMxYTdiNDEwMjdkNThlOGEzYzQ1MzljNDFkNzM1Y2JjZDExYWJmODNkZmY0YTE5Y2FkNzAzZWIxNjE2MDZlYThkMDJhMTM2OTlhZGVlNWEwYWIzZjRhYzhlMDZmYmE2Njc1N2NiOWE=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    from: bdscompanyvietnam@gmail.com
    base-url: http://127.0.0.1:9000
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  audit-events:
    retention-period: 30 # Number of days before audit events are deleted.

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

application:
  fire-base:
    {
      'type': 'service_account',
      'project_id': 'bdsdonnv',
      'private_key_id': '7b1f3a64e1e5cb5f4c44aeeae36fbb486972be95',
      'private_key': "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC09Bo+P+3ixBaG\nyPcMiK6vFLjL1gh4qBW2b3lImAOaQjMhCXrusSm+bvtweCk3i7VU+anQ+mwmF4Sp\nLFvIbG4rX5iN5unR+9PrKpsH6O5KI6mwnuQpSMnGUXYW/mLKZ5tsBK+FQezwRY2Z\nFAOcv2rgW7aa19xJqtpuDFbq2oucSlCBcFUhu+rpy7OBTzSDSgHfomqne/D9ISWL\nk6NFE5bWmSeUD8sH7omA9dly+mkGb5p8+JZXcxMooF7OEnBAkvyJpRoI/QiJTbeq\n6SivshuLPOsFhxBe8wf13YFJHjg868NzP506C82PD+lOpuzhKMo02ISkqzjdzrJP\nDRa+v3r1AgMBAAECggEAFJdAUzwQFEFO9OhyYE0/X3His2M4FI6/5cIakX2mz0tg\nKQ68m+OyBdb4KqypuAXgTPqZ7ctJOi5r7Jo9GXnpMWtP3zna+oeG7lgrSwOg9fPH\n7+6stNvxBe2oG+a3lCOlBm4kEOxXC2JGwhgKbzBC96PIDCerDADymRozW8choteL\nBNfkvYu0drTGdF3vZ1Gkvmy1DYKp9ojh0DbAGZazvkWKUCV7p9R5Ydq+1OsmEmYS\nB6jryaLTi19Geh8+ZPzj0wLDQg+vHtfoXhYrDhQIHSMhWtRBcSWRjzE4ybQudEl5\np9BtHE14LSsI9u1kS9WDB5TEWoZIJ3lsM4PNJoEbkwKBgQDYLhsXDVKSSbXDnHIG\nrGHVXWo1s6rAhi1Ye6YEs8tD/Ai8IZ+l444+HruwL/tYlTNNuZBpH7C8acLssAWZ\nhtcjMSwaEoIpy/BMHHW0cxHlPEXe9zInG+Ogv4j1zjIxZ7gV34+6YRS0rzONUuYG\nNtblZWxHpoiO2ZQGNOjQVTl+UwKBgQDWSOZ7FRmVyJEz8bBwyYjcQ9SSLe1A1Qzh\n+1RM6DUbFsy/fgxCAEak7w2HUHzksJmSM15yTPhHZOpBV00rKgKsf+mRnzh044la\nQWI72EhThAKmcmknwlj18EHnzrejD1sN1uXwG31n10npgFUnxwqvccQndYpLNhrc\ninZdTGMolwKBgQDEFBWoNAJIA6lk0lquaN6X+5HhQaRH2av5jLWJoFZmxIxbr5ex\njJOxDokohmzQ7QtKnVw5rW/NhZQywHljxmUOW4Rn5Y/AP2Umc83jLVf291NcqBQK\nWwZ9AB1G7o6iNzRGSq9/2pxAQoVc0usmicki6nprBsbn4rubYZQlmpd6VwKBgQCp\nBB8m/eGMTwKYog21KIEWmznTgv4boO/kXsSDVLRuhXFBqT4p4OXXueZF0KpyBwla\nU8IvDZ7XUTWkDCQF48DwJoQoJBn3uHDiC6hb46BIn1snxh5DCfv5IGQbXuVha/85\nz0LWPBiSCzF1R4/jLA+1ilpZdVB7OlW9lkj+Ff4wSQKBgQCdHBKvDIjy28OcU0e0\nbwXQTjBYPHqJGHmeSVrVQIdBiBDyvO8ttUq7zHJqayYQNg+NAHLlNmM2VAVuzqeS\n1DEjZGY1VeawM7sCGZ2xY7IoDmPOCuDrfFt5Zlpxo2irS4TvvQckO3nXXZJWZTWE\nmdbKqsGPC4ZCIxyF8oLZhswRPw==\n-----END PRIVATE KEY-----\n",
      'client_email': 'firebase-adminsdk-4dbnr@bdsdonnv.iam.gserviceaccount.com',
      'client_id': '110177302321852333246',
      'auth_uri': 'https://accounts.google.com/o/oauth2/auth',
      'token_uri': 'https://oauth2.googleapis.com/token',
      'auth_provider_x509_cert_url': 'https://www.googleapis.com/oauth2/v1/certs',
      'client_x509_cert_url': 'https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-4dbnr%40bdsdonnv.iam.gserviceaccount.com',
    }

  base-location: C:\images\
